export const BOARDS_FETCHED = "BOARDS_FETCHED"
export const BOARD_FETCHED = "BOARD_FETCHED"
export const BOARD_ADDED = "BOARD_ADDED"
export const ADD_LIST = "ADD_LIST"
export const LIST_ADDED = "LIST_ADDED"
export const LIST_UPDATED = "LIST_UPDATED"
export const LIST_DELETED = "LIST_DELETED"
export const ITEM_ADDED = "ITEM_ADDED"
